apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-app
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: crccheck/hello-world
