apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-app
  annotations:
    app.oam.dev/publishVersion: aa193e45
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: crccheck/hello-world
